version: "3.8"
services:
  shiny:
    image: "shrektan/rdocker4working:latest"
    deploy:
      replicas: 2
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.http.routers.shiny.rule=Host(`shiny.docker.localhost`)
          - traefik.http.routers.shiny.entrypoints=http
          - traefik.http.services.shiny.loadbalancer.server.port=3838
          - traefik.http.services.shiny.loadbalancer.sticky=true
          - traefik.http.services.shiny.loadbalancer.sticky.cookie.name=traefik_shiny_cookie
          - traefik.http.services.shiny.loadbalancer.sticky.cookie.httpOnly=true
          - traefik.http.services.shiny.loadbalancer.sticky.cookie.secure=false
    volumes:
      - ./app:/app
    command: ['Rscript', '-e', "shiny::runApp('/app', host = '0.0.0.0', port = 3838)"]
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
